<?php
namespace ICANS\Component\IcansLoggingComponent\Flume;
/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * @generated
 */

/**
 * @codeCoverageIgnore
 * @codingStandardsIgnoreFile
 */
final class EventStatus
{
    const ACK = 0;
    const COMMITED = 1;
    const ERR = 2;
    static public $__names = array(
        0 => 'ACK',
        1 => 'COMMITED',
        2 => 'ERR',
    );
}