<?php
namespace ICANS\Component\IcansLoggingComponent\Flume;
/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * @generated
 */

/**
 * @codeCoverageIgnore
 * @codingStandardsIgnoreFile
 */
final class Priority
{
    const FATAL = 0;
    const ERROR = 1;
    const WARN = 2;
    const INFO = 3;
    const DEBUG = 4;
    const TRACE = 5;
    static public $__names = array(
        0 => 'FATAL',
        1 => 'ERROR',
        2 => 'WARN',
        3 => 'INFO',
        4 => 'DEBUG',
        5 => 'TRACE',
    );
}