<?php
namespace ICANS\Component\IcansLoggingComponent\Flume;
/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * @generated
 */

/**
 * @codeCoverageIgnore
 * @codingStandardsIgnoreFile
 */
interface ThriftFlumeEventServerIf
{
    public function append(\ICANS\Component\IcansLoggingComponent\Flume\ThriftFlumeEvent $evt);

    public function close();
}