<?php
namespace ICANS\Component\IcansLoggingComponent\Flume;
/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * @generated
 */
use Thrift\Base\TBase;

use Thrift\Type\TType;

// HELPER FUNCTIONS AND STRUCTURES
/**
 * @codeCoverageIgnore
 * @codingStandardsIgnoreFile
 */
class ThriftFlumeEventServer_append_args extends TBase
{
    static $_TSPEC;

    public $evt = null;

    public function __construct($vals = null)
    {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'evt',
                    'type' => TType::STRUCT,
                    'class' => '\ICANS\Component\IcansLoggingComponent\Flume\ThriftFlumeEvent',
                ),
            );
        }
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'ThriftFlumeEventServer_append_args';
    }

    public function read($input)
    {
        return $this->_read('ThriftFlumeEventServer_append_args', self::$_TSPEC, $input);
    }

    public function write($output)
    {
        return $this->_write('ThriftFlumeEventServer_append_args', self::$_TSPEC, $output);
    }
}