<?php
namespace ICANS\Component\IcansLoggingComponent\Flume;
/**
 * Autogenerated by Thrift Compiler (0.9.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * @generated
 */
use Thrift\Base\TBase;

use Thrift\Type\TType;

/**
 * @codeCoverageIgnore
 * @codingStandardsIgnoreFile
 */
class ThriftFlumeEvent extends TBase
{
    static $_TSPEC;

    public $timestamp = null;
    public $priority = null;
    public $body = null;
    public $nanos = null;
    public $host = null;
    public $fields = null;

    public function __construct($vals = null)
    {
        if (!isset(self::$_TSPEC)) {
            self::$_TSPEC = array(
                1 => array(
                    'var' => 'timestamp',
                    'type' => TType::I64,
                ),
                2 => array(
                    'var' => 'priority',
                    'type' => TType::I32,
                ),
                3 => array(
                    'var' => 'body',
                    'type' => TType::STRING,
                ),
                4 => array(
                    'var' => 'nanos',
                    'type' => TType::I64,
                ),
                5 => array(
                    'var' => 'host',
                    'type' => TType::STRING,
                ),
                6 => array(
                    'var' => 'fields',
                    'type' => TType::MAP,
                    'ktype' => TType::STRING,
                    'vtype' => TType::STRING,
                    'key' => array(
                        'type' => TType::STRING,
                    ),
                    'val' => array(
                        'type' => TType::STRING,
                    ),
                ),
            );
        }
        if (is_array($vals)) {
            parent::__construct(self::$_TSPEC, $vals);
        }
    }

    public function getName()
    {
        return 'ThriftFlumeEvent';
    }

    public function read($input)
    {
        return $this->_read('ThriftFlumeEvent', self::$_TSPEC, $input);
    }

    public function write($output)
    {
        return $this->_write('ThriftFlumeEvent', self::$_TSPEC, $output);
    }
}